# Generated by Django 4.2.4 on 2023-08-07 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Skills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "skill",
                    models.CharField(
                        default="Не заполнено",
                        max_length=50,
                        verbose_name="Название скила",
                    ),
                ),
                (
                    "opisanie",
                    models.CharField(
                        default="Не заполнено",
                        max_length=250,
                        verbose_name="Краткое описание",
                    ),
                ),
                ("full_text", models.TextField(verbose_name="Примеры реализации")),
                (
                    "cat",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="skills.category",
                    ),
                ),
            ],
        ),
    ]
